import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css';
import { GoogleOAuthProvider } from "@react-oauth/google"
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter(X) Clone - Siddharth S',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex h-screen w-screen overflow-hidden pt-4 px-28"}>
        <GoogleOAuthProvider clientId="1099282194285-nhpo44t56d1l0lfikdrko7lqksg83q70.apps.googleusercontent.com">
            {children}
          <Toaster/>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
